"""Prompt-attention syntax parsing and embedding weighting.

The parser intentionally lives in Sodalite rather than adopting a WebUI
implementation. It recognizes the widely-used parentheses/brackets notation
and produces ordinary prompt text plus a multiplier for each text fragment.
"""

from dataclasses import dataclass

import torch

_EMPHASIS = 1.1


@dataclass(frozen=True)
class PromptFragment:
    """A consecutive span of prompt text with one attention multiplier."""

    text: str
    weight: float


def parse_prompt_attention(prompt: str) -> list[PromptFragment]:
    """Parse ``()``/``[]`` attention syntax without changing ordinary prompts.

    Parentheses multiply attention by 1.1, brackets divide it by 1.1, and a
    parenthesized suffix such as ``(cat:1.3)`` sets that group to 1.3 times its
    surrounding weight. Backslashes escape punctuation.
    """
    fragments: list[PromptFragment] = []
    group_starts: list[tuple[int, float]] = []
    buffer: list[str] = []

    def flush(weight: float = 1.0) -> None:
        if buffer:
            fragments.append(PromptFragment("".join(buffer), weight))
            buffer.clear()

    index = 0
    while index < len(prompt):
        character = prompt[index]
        if character == "\\" and index + 1 < len(prompt):
            buffer.append(prompt[index + 1])
            index += 2
            continue
        if character in "([":
            flush()
            group_starts.append((len(fragments), _EMPHASIS if character == "(" else 1 / _EMPHASIS))
        elif character in ")]":
            flush()
            if group_starts:
                start, default_weight = group_starts.pop()
                weight = default_weight
                if character == ")" and start < len(fragments):
                    last = fragments[-1]
                    prefix, separator, explicit = last.text.rpartition(":")
                    if separator:
                        try:
                            weight = float(explicit)
                        except ValueError:
                            pass
                        else:
                            fragments[-1] = PromptFragment(prefix, last.weight)
                for fragment_index in range(start, len(fragments)):
                    fragment = fragments[fragment_index]
                    fragments[fragment_index] = PromptFragment(
                        fragment.text, fragment.weight * weight
                    )
            else:
                buffer.append(character)
        else:
            buffer.append(character)
        index += 1

    flush()
    return _merge_fragments(fragments)


def has_attention_syntax(prompt: str) -> bool:
    """Return whether parsing applies a non-default weight to any prompt span."""
    return any(fragment.weight != 1.0 for fragment in parse_prompt_attention(prompt))


def apply_attention_weights(
    prompt_embeds: torch.Tensor, tokenizer, fragments: list[PromptFragment]
) -> torch.Tensor:
    """Scale token embeddings while preserving their average magnitude.

    This reuses the embeddings generated by diffusers, so it adds neither a
    second text-encoder pass nor a denoising step. CLIP special/padding tokens
    retain weight 1.0.
    """
    token_weights: list[float] = []
    for fragment in fragments:
        token_ids = tokenizer(fragment.text, add_special_tokens=False).input_ids
        token_weights.extend([fragment.weight] * len(token_ids))

    sequence_length = prompt_embeds.shape[1]
    token_weights = [1.0, *token_weights[: sequence_length - 2], 1.0]
    token_weights.extend([1.0] * (sequence_length - len(token_weights)))
    weights = torch.tensor(token_weights, device=prompt_embeds.device, dtype=prompt_embeds.dtype)
    weights = weights.view(1, sequence_length, 1)

    original_mean = prompt_embeds.abs().mean(dim=(1, 2), keepdim=True)
    weighted = prompt_embeds * weights
    weighted_mean = weighted.abs().mean(dim=(1, 2), keepdim=True).clamp_min(
        torch.finfo(prompt_embeds.dtype).eps
    )
    return weighted * (original_mean / weighted_mean)


def _merge_fragments(fragments: list[PromptFragment]) -> list[PromptFragment]:
    merged: list[PromptFragment] = []
    for fragment in fragments:
        if not fragment.text:
            continue
        if merged and merged[-1].weight == fragment.weight:
            previous = merged[-1]
            merged[-1] = PromptFragment(previous.text + fragment.text, previous.weight)
        else:
            merged.append(fragment)
    return merged
